name: Add Comment
description: "Add or modify comment in the PR"
inputs:
  marker:
    description: "Text used to find the comment to modify"
    required: true
  markdown_path:
    description: "Path to the file containing markdown"
    required: true

runs:
  using: "composite"
  steps:
    - name: Post/Update PR Performance Comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const marker = "${{ inputs.marker }}";
          const body = fs.readFileSync("${{ inputs.markdown_path }}", 'utf8');
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          const existing = comments.find(c => c.body && c.body.startsWith(marker));
          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }