name: Performance

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    timeout-minutes: 10
    strategy:
      fail-fast: false

    defaults:
      run:
        shell: bash

    name: "Performance"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Docker Image
        run: |
          docker build -f performance/Dockerfile -t dst-test-node .

      - name: Run
        run: |
          ./performance/runner.sh
